package com.xe.b2b.data.access.dao;

import com.xe.b2b.data.access.dao.base.BaseMapper;
import com.xe.b2b.data.access.model.MenuEntity;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface MenuDao extends BaseMapper<MenuEntity> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2b_menu
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, action, sort, code, created_by, create_date, parent_code, icon",
        "from b2b_menu",
        "where code = #{id}"
    })
    @ResultMap("baseMenuMap")
    MenuEntity selectByPrimaryKey(String id);

    @Select({
        "select * from b2b_menu where parent_code is null or parent_code='' order by sort"
    })
    @ResultMap("SonResultMap")
    List<MenuEntity> selectAllNullParent();



    @Select({
        "select * from b2b_menu where code in(select menu_code from b2b_role_menu where role_code=#{roleCode})"
    })
    @ResultMap("baseMenuMap")
    List<MenuEntity> selectByRole(String roleCode);


    @Select({
            "select * from b2b_menu where parent_code=#{parentCode}"
    })
    @ResultMap("baseMenuMap")
    List<MenuEntity> selectEffectiveByParent(String parentCode);

    @Select({
            "select * from b2b_menu",
            " where code in ( select menu_code  from b2b_role_menu where role_code in (",
            " select role_code from b2b_user_role where WORK_ID=#{workId} and is_active=1 )",
            " and is_active=1) and is_active=1 order by sort"
    })
    @ResultMap("baseMenuMap")
    List<MenuEntity> selectAllNullParentByUser(String workId);
}