package com.xe.b2b.data.access.dao;

import com.xe.b2b.data.access.dao.base.BaseMapper;
import com.xe.b2b.data.access.model.RoleMenuEntity;

import java.util.List;

public interface RoleMenuDao extends BaseMapper<RoleMenuEntity> {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tbl_role_menu
//     *
//     * @mbggenerated
//     */
//    @Insert({
//        "insert into tbl_role_menu (role_id, menu_id)",
//        "values (#{roleId,jdbcType=VARCHAR}, #{menuId,jdbcType=VARCHAR})"
//    })
//    int insert(RoleMenuEntity record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tbl_role_menu
//     *
//     * @mbggenerated
//     */
//    int insertSelective(RoleMenuEntity record);
//
//
//
//    @Delete({
//        "delete from tbl_role_menu",
//        "where role_id=#{roleId}"
//    })
//    int deleteByRole(String roleId);
//
//
//    @Delete({
//        "delete from tbl_role_menu",
//        "where menu_id=#{menuId}"
//    })
//    int deleteByMenu(String menuId);
//
//
//
//    @Select({
//        "select * from tbl_role_menu",
//        "where role_id=#{roleId}"
//    })
//    @ResultMap("BaseResultMap")
    List<RoleMenuEntity> selectByRoleCode(String roleCode);
    
    
}